pipeline {
    agent any

    environment {
      // Define Docker Hub login credentials
      DOCKER_CREDENTIALS = credentials('docker-hub-credentials')
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    // Navigate to the directory
                    dir('docker/client') {
                        // Builds the React app's Docker image
                        sh 'docker build -t willondrik/react-app:latest .'
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_HUB_USER', passwordVariable: 'DOCKER_HUB_PASS')]) {
                        // Login to Docker Hub using login credentials
                        sh 'echo $DOCKER_HUB_PASS | docker login -u $DOCKER_HUB_USER --password-stdin'
                        // Pushes the Docker image to Docker Hub
                        sh 'docker push willondrik/react-app:latest'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    // Navigate to Kubernetes directory
                    dir('kubernetes') {
                        // Apply Kubernetes configuration
                        sh 'kubectl apply -f app-deployment.yml'
                        sh 'kubectl apply -f app-horizontal-deployment.yml'
                        sh 'kubectl apply -f app-service.yml'
                    }

                    // Navigate to Grafana directory
                    dir('grafana') {
                        sh 'kubectl apply -f grafana-deployment.yml'
                        sh 'kubectl apply -f grafana-service.yml'
                    }
                }
            }
        }
    }
}
