pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    // Navigate to the directory
                    dir('docker/client') {
                        // Builds the React app's Docker image
                        sh 'docker build -t react-app:latest .'
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                // Pushes the Docker image to Docker Hub
                sh 'docker push react-app:latest'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    // Navigate to Kubernetes directory
                    dir('kubernetes') {
                        // Apply Kubernetes configuration
                        sh 'kubectl apply -f app-deployment.yml'
                        sh 'kubectl apply -f app-horizontal-deployment.yml'
                        sh 'kubectl apply -f app-service.yml'
                    }

                    // Navigate to Grafana directory
                    dir('grafana') {
                        sh 'kubectl apply -f grafana-deployment.yml'
                        sh 'kubectl apply -f grafana-service.yml'
                    }
                }
            }
        }
    }
}
