apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: LoadBalancer # Use NodePort or LoadBalancer depending on your environment
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: react-app
