apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: app-horizontal-deployment
spec:
  scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: react-app
minReplicas: 2
maxReplicas: 6
metrics:
- type: Resource
  resource: cpu
  targetAverageUtilization: 50


  # apply it to my kubernetes cluser: kubectl apply -f app-horizontal-deployment.yaml

  # kubernetes will now automatically adjust the number of replicas based on the cpu utilization of your application
    # to monitor the HPA's behaviour: kubectl get hpa